# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  nationbuilder.api:
    class: AppBundle\Service\APIService
    arguments: ["%oauth.client_id%", "%oauth.client_secret%", "%oauth.base_url%", "%oauth.test_token%"]
